# Generated by Django 5.1.2 on 2024-11-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('RIB', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'comptes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confirme', models.BooleanField(default=False)),
                ('from_account', models.ForeignKey(db_column='from_account', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='transactions.compte')),
                ('to_account', models.ForeignKey(db_column='to_account', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='transactions.compte')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
